#!/usr/bin/env python2.7

from argparse import ArgumentParser
from os import mkdir, chmod
from os.path import dirname, realpath, join as joinpath, exists
from sys import argv
from subprocess import call
from fitlib import fitDir, cacheDir, repoDir, gitDir, tempDir, commitsDir, savesDir
from fitlib import mergeMineFitFile, readFitFile, firstTimeFile, printAsText, getHashForRevision
from fitlib import hooks, objects, merge, changes
import stat

def main():
    opts = getOpts()
    firstTimeRepoSetup(opts.no_hooks)

    if len(argv) > 1 and argv[1] in ('save', 'restore', 'get', 'put'):
        if argv[1] == 'save':
            if not merge.isMergeInProgress():
                changes.save(readFitFile(), pathArgs=opts.paths)
                return

            if opts.paths:
                print 'error: git-fit save can only be run without PATH arguments when merging.'
                print merge.conflictMsg
            elif merge.resolve():
                print '\nYay! Successfully resolved all conflicts! Once there are no other git conflicts'
                print 'remaining for this merge, you can go ahead and commit the changes (which'
                print 'include the .fit file).'
        elif argv[1] == 'restore':
            changes.restore(readFitFile(), pathArgs=opts.paths)
        elif argv[1] == 'get':
            objects.get(readFitFile(rev='HEAD'), summary=opts.summary, showlist=opts.list, quiet=opts.quiet, pathArgs=opts.paths)
        elif argv[1] ==  'put':
            objects.put(readFitFile(rev='HEAD'), summary=opts.summary, showlist=opts.list, quiet=opts.quiet)
    elif opts.merge_help:
        print merge.instructions
    elif not opts.git:
        if merge.isMergeInProgress():
            resolutions = merge.getResolutions()
            if not resolutions:
                return
            fitData, resolutions = resolutions[0], resolutions[1:]
        else:
            fitData = readFitFile()
            resolutions = None
        changes.printStatus(fitData, pathArgs=opts.paths, legend=opts.legend, showall=opts.all, mergeInfo=resolutions)
    elif opts.git == 'pre-commit':
        hooks.preCommit()
    elif opts.git == 'post-commit':
        hooks.postCommit()
    elif opts.git_head_change:
        if (
            (
                opts.git == 'post-merge'
                or (opts.git == 'post-rewrite' and opts.paths[0] == 'rebase')
                or (opts.git == 'post-checkout' and opts.paths[0] != opts.paths[1] and opts.paths[2] == '1')
            )
            and getHashForRevision('HEAD@{1}')
        ):
            hooks.postCheckout()
    elif opts.git == 'merge-driver':
        merged = merge.mergeDriver(*(opts.paths[:3]))
        
        return exit(0 if merged else 1)
    elif opts.git == 'text-output':
        printAsText(readFitFile(opts.paths[0]))

# This will be used to check whether we need to run (or re-run after changes to git-fit)
# this first-time repo setup
_firstTimeCounter = 0

def firstTimeRepoSetup(nohooks=False):
    global _firstTimeCounter
    if not exists(fitDir):
        print 'Preparing this repository for use with git-fit...'
        mkdir(fitDir)
        mkdir(cacheDir)
        mkdir(commitsDir)
        mkdir(savesDir)
        mkdir(tempDir)
        
        print 'Restoring working tree with current fit items...'
        changes.restore(readFitFile(), quiet=True)
    elif exists(firstTimeFile):
        firstTimeCount = int(open(firstTimeFile).read())

        if firstTimeCount == _firstTimeCounter:
            return

        if firstTimeCount > _firstTimeCounter:
            print 'You are running a version of git-fit that is OLDER than the version with which'
            print 'this repo has been used before. Please check that your PATH points to the'
            print 'latest copy of git-fit you have on your system. git-fit will now exit...'
            exit(1)

    f = open(firstTimeFile, 'w')
    f.write("%d"%_firstTimeCounter)
    f.close()

    f = open(joinpath(gitDir, 'info', 'attributes'), 'w')
    f.write('\n.fit -fit merge=fitfile diff=fitfile\n')
    f.close()

    f = open(joinpath(gitDir, 'info', 'exclude'), 'w')
    f.write('\n.fit\n')
    f.close()

    if nohooks:
        return

    def createHook(name, args=''):
        f = open(joinpath(gitDir, 'hooks', name), 'w')
        f.write('\n$fitt --git=%s %s\n'%(name,args))
        f.close()
        chmod(joinpath(gitDir, 'hooks', name), stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)
    
    createHook('pre-commit')
    createHook('post-commit')
    createHook('post-checkout', '--git-head-change ${1} ${2} ${3}')
    createHook('post-merge', '--git-head-change')
    createHook('post-rewrite', '--git-head-change  ${1}')

    cmd = '''
        git config merge.fitfile.name 'Merge driver to auto-resolve .fit file conflicts when possible'
        git config merge.fitfile.driver '$fitt --git=merge-driver %O %A %B'
        git config diff.fitfile.textconv '$fitt --git=text-output'
        git config diff.fitfile.cachetextconv true
    '''
    call('set -e\n' + cmd, shell=True)

def getOpts():
    parser = None
    args = None
    if len(argv) == 1 or argv[1] not in ('save', 'restore', 'get', 'put'):
        if '-h' in argv:
            print helpUsage
            exit()

        if '--help' in argv:
            print helpIntro + helpUsage + helpFull
            exit()
        parser = ArgumentParser(add_help=False, usage='git-fit [--help] [--legend] [--all] [<PATH>...]')
        parser.add_argument('--git-head-change', action='store_true')
        parser.add_argument('--git', choices=('post-commit','pre-commit','post-checkout','post-merge','post-rewrite','merge-driver','text-output'))
        parser.add_argument('--all', '-a', action='store_true')
        parser.add_argument('--legend', '-l', action='store_true')
        parser.add_argument('--merge-help', '-m', action='store_true')
        parser.add_argument('paths', nargs='*')
    elif argv[1] in ('save', 'restore'):
        usage = 'git-fit %s [--help] [<PATH>...]'%(argv[1])
        if '--help' in argv[2:]:
            print 'usage:', usage
            print (cmdSaveHelp if argv[1] == 'save' else cmdRestoreHelp)
            exit()
        if '-h' in argv[2:]:
            print 'usage:', usage
            exit()
        parser = ArgumentParser(add_help=False, usage=usage)
        parser.add_argument('paths', nargs='*')
        args = argv[2:]
    elif argv[1] in ('get', 'put'):
        usage = 'git-fit %s [--help] %s'%(argv[1], cmdGetUsage if argv[1] == 'get' else cmdPutUsage)
        if '--help' in argv[2:]:
            print 'usage:', usage
            print (cmdGetHelp if argv[1] == 'get' else cmdPutHelp)
            print 'Options:',cmdGetPutOpts
            exit()
        if '-h' in argv[2:]:
            print 'usage:', usage
            exit()
        parser = ArgumentParser(add_help=False, usage=usage)
        parser.add_argument('--summary', '-s', action='store_true')
        parser.add_argument('--list', '-l', action='store_true')
        parser.add_argument('--quiet', '-q', action='store_true')
        if argv[1] == 'get':
            parser.add_argument('paths', nargs='*')
        args = argv[2:]

    parser.add_argument('--no-hooks', action='store_true')
    return parser.parse_args(args)

helpIntro='''
git-fit has five basic operations, status, save/restore, and get/put. All
operations except 'put' can optionally take one or more paths to select a
subset of items. Use -h/--help to get brief/detailed help on any operation.
Without any subcommand, git-fit shows the status of fit items in the working
tree. This working tree status is always relative to the information recorded
in the current working tree .fit file. However, a diff of changes between any
two versions of the .fit file (i.e. HEAD, index, different branch, older
revision, etc.) can be viewed by using the usual diff-basedd git commands,
such as git-diff and git-show.
'''

helpUsage='''
Usage:
    git-fit [<COMMAND>] [-h] [--help]

    git-fit         [--legend] [--all] [--merge-help] [<PATH>...]
    git-fit save    [<PATH>...]
    git-fit restore [<PATH>...]
    git-fit get     [--summary] [--list] [--quiet] [<PATH>...]
    git-fit put     [--summary] [--list] [--quiet]
'''

cmdGetPutOpts='''
    -s, --summary   Do not transfer. Instead, show a summary of what would be transferred.
    -l, --list      Do not transfer. Instead, list all the items that would be transferred.
    -q, -quiet      Supress transfer progress output.
'''

helpFull='''
Commands:
    (none)    Shows status of fit items in the working tree.

    save      Updates .fit file with current changes to fit items in the working tree.
    restore   Discards any changes to fit items in the working tree. (opposite of save).
    get       Copies objects FROM remote location and/or populates working tree.
    put       Copies objects TO remote location from local cache.

Options:
    -h              Show brief help for the command.
    --help          Show full help for the command.

    status
    -l, --legend       Print a legend showing what status symbols mean.
    -a, --all          List even those items whose status is unchanged.
    -m, --merge-help   Print out instructions for resolving fit conflicts.

    get/put''' + cmdGetPutOpts

cmdGetUsage = '[--summary] [--list] [--quiet] [<PATH>...]'
cmdPutUsage = '[--summary] [--list] [--quiet]'
cmdSaveHelp = '''
Updates .fit file with current changes to fit items in the working tree. The .fit file is
also git-added (which you can then commit along with any other non-fit changes). After
running this command, any items that were shown as modified, added, removed, or untracked
(*, +, -, ~) by the status output of git-fit are no longer shown as such, since those
changes have been recorded in the .fit file. However, any potential commit-aborting items
continue to be shown in the status.

The IMPORTANT thing to remember is that the .fit file should NEVER be manually changed or
manually git-add'ed. Both the updating/changing of the .fit file and it's staging to the
git index should be done completely through the git-fit save command. It is, however,
completely safe to git-reset the .fit file (i.e. unstage it) after it has been
git-fit save'd. It is also okay to do multiple git-fit save's, one after another, without
actually having git-commit'ed an existing staged/saved .fit file.

'''
cmdRestoreHelp = '''
Discards any changes to fit items in the working tree. (THIS CANNOT BE UNDONE). Notice that
this operation is the opposite of the save operation. This will IRREVERSIBLY discard all
uncommitted changes to your fit-tracked items, bringing your working tree to a pristine
condition with respect to those objects currently being tracked by fit (so use this command
with caution). In other words, whatever modified, added, or removed (*, +, -) items you see in
the git-fit status output before running restore, you will no longer see after running
restore. Items marked to be untracked from fit (~) and any potential commit-aborting items will
continue to be shown and cannot be "restored".
'''
cmdGetHelp = '''
Copies objects FROM remote location and/or populates working tree from local cache. Until this
is done, any action in your project that requires the actual contents of these items will not
work as expected. Only items that are not already in the working tree or local fit cache will
be downloaded. If there are changes to fit items in the working tree, git-fit get does not 
affect them.
'''
cmdPutHelp = '''
Copies objects TO remote location from local cache. Until this is done, people who are using
your commits will not have access to these items. If an item already exist in the external
store due to a previous upload (either by you or someone else), the item will be skipped (but
this cannot be determined without actually starting the upload process first). Unlike git-fit
get, git-fit put does not take optional PATH arguments -- all items needing to be uploaded for
the HEAD must be uploaded to fulfill the commit.
'''

if __name__ == '__main__':
    main()
